'use strict'
// Secure IPC bridge. The renderer gets exactly this API on window.relay — nothing else.
const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('relay', {
  list:          () => ipcRenderer.invoke('relay:list'),
  usage:         () => ipcRenderer.invoke('relay:usage'),
  captureSession:(input) => ipcRenderer.invoke('relay:capture-session', input),
  create:        (input) => ipcRenderer.invoke('relay:create', input),
  cancel:        (id) => ipcRenderer.invoke('relay:cancel', id),
  remove:        (id) => ipcRenderer.invoke('relay:delete', id),
  retry:         (id) => ipcRenderer.invoke('relay:retry', id),
  runNow:        (id) => ipcRenderer.invoke('relay:run-now', id),
  resumeAtReset: (id) => ipcRenderer.invoke('relay:resume-at-reset', id),
  getSettings:   () => ipcRenderer.invoke('relay:settings:get'),
  setSettings:   (patch) => ipcRenderer.invoke('relay:settings:set', patch),
  listSessions:  () => ipcRenderer.invoke('relay:sessions:list'),
  getLog:        (logPath) => ipcRenderer.invoke('relay:logs:get', logPath),
  openLogs:      () => ipcRenderer.invoke('relay:logs:open'),
  claudeUsage:   () => ipcRenderer.invoke('relay:claude-usage'),
  claudeLogin:   () => ipcRenderer.invoke('relay:claude-login'),
  claudeLogout:      () => ipcRenderer.invoke('relay:claude-logout'),
  update:      (id, patch) => ipcRenderer.invoke('relay:update', id, patch),
  setupSkill:  () => ipcRenderer.invoke('relay:setup-skill'),
  onCtxAction: (cb) => ipcRenderer.on('relay:ctx-action', (_e, taskId, action) => cb(taskId, action)),
  statuslinePath:  () => ipcRenderer.invoke('relay:statusline-path'),
  onChanged:     (cb) => ipcRenderer.on('relay:changed', () => cb()),
  onUpdateAvailable: (cb) => ipcRenderer.on('relay:update-available', (_e, version) => cb(version)),
  onUpdateReady:     (cb) => ipcRenderer.on('relay:update-ready', () => cb()),
  getLoginItem:  () => ipcRenderer.invoke('relay:login-item:get'),
  setLoginItem:  (val) => ipcRenderer.invoke('relay:login-item:set', val),
  version:       () => ipcRenderer.invoke('relay:version'),
  installUpdate:  () => ipcRenderer.invoke('relay:install-update'),
  browseFolder:  () => ipcRenderer.invoke('relay:browse-folder'),
})
